version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - minio
      - redis

  pgdb:
    # image: postgres
    image: postgres:16.0-alpine
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LANG=C.UTF-8
    volumes:
      - pgdbdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2022-10-15T19-57-03Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: .env
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=YES

volumes:
  pgdbdata: null