# Generated by Django 4.2.7 on 2024-10-15 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billoperat',
            options={'verbose_name': 'м-м', 'verbose_name_plural': 'м-м'},
        ),
        migrations.AddField(
            model_name='bill',
            name='image_back',
            field=models.ImageField(default='images/default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(choices=[(1, 'Действует'), (2, 'Удален')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.CharField(default='1988', max_length=100),
        ),
        migrations.AddField(
            model_name='operat',
            name='address',
            field=models.CharField(default='г. Москва, ул. Мирная 11, д. 2', max_length=255),
        ),
        migrations.AddField(
            model_name='operat',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operat',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterModelTable(
            name='billoperat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='operat',
            table='operation',
        ),
    ]
