# Generated by Django 4.2.4 on 2024-11-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billoperat',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='billoperat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='operat',
            name='count',
        ),
        migrations.AddField(
            model_name='operat',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='billoperat',
            constraint=models.UniqueConstraint(fields=('bill', 'operat'), name='unique_BillOperat'),
        ),
    ]
