# Generated by Django 4.2.4 on 2024-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operat',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
