# Generated by Django 4.2.7 on 2024-10-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_billoperat_options_bill_image_back_bill_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billoperat',
            table='bill_operat',
        ),
    ]
