# Generated by Django 4.2.4 on 2024-11-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_billoperat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billoperat',
            options={'verbose_name': 'Купюра-Операция', 'verbose_name_plural': 'Купюры-Операции'},
        ),
        migrations.RemoveConstraint(
            model_name='billoperat',
            name='unique_BillOperat',
        ),
        migrations.RemoveField(
            model_name='operat',
            name='success',
        ),
        migrations.AddField(
            model_name='bill',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operat',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='billoperat',
            unique_together={('bill', 'operat')},
        ),
    ]
