# Generated by Django 4.2.4 on 2024-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_billoperat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='success',
        ),
        migrations.RemoveField(
            model_name='operat',
            name='count',
        ),
        migrations.AddField(
            model_name='operat',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
