# Generated by Django 4.2.7 on 2024-10-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_billoperat_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billoperat',
            options={'verbose_name': 'Купюра-Снятие', 'verbose_name_plural': 'Купюры-Снятие'},
        ),
        migrations.RenameField(
            model_name='billoperat',
            old_name='bill',
            new_name='id_bill_mm',
        ),
        migrations.RenameField(
            model_name='billoperat',
            old_name='operat',
            new_name='id_operat_mm',
        ),
        migrations.AlterUniqueTogether(
            name='billoperat',
            unique_together={('id_bill_mm', 'id_operat_mm')},
        ),
    ]
