# Generated by Django 4.2.7 on 2024-10-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_billoperat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoperat',
            name='value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
