# Generated by Django 4.2.4 on 2024-11-23 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_bill_success_remove_operat_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operat',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менежер'),
        ),
    ]
