# Generated by Django 4.2.7 on 2024-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_billoperat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.CharField(default='images/default.png'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='image_back',
            field=models.CharField(default='images/default.png'),
        ),
    ]
